task_name: &TASK_NAME diffusion_toy
dataset:
  name: get_diffusion_toy_data

model:
  name: DiffusionToy

optimizer:
  name: Adam
  params:
    lr: 0.001
    warmup_steps: 1000
    total_steps: 10000
    start_factor: 0.01
    eta_min: 1.0e-6

logger:
  name: DiffusionToyLogger
  params:
    img_dump_dir: images