task_name: &TASK_NAME diffusion_ddpm
dataset:
  name: get_diffusion_toy_data

model:
  name: DiffusionToy
  params:
    diffusion_alg: ddpm
    denoise_steps: 500


optimizer:
  name: Adam
  params:
    lr: 0.001

logger:
  name: DiffusionToyLogger
  params:
    img_dump_dir: images