task_name: &TASK_NAME diffusion_toy
dataset:
  name: get_diffusion_toy_data

model:
  name: LitAutoEncoder
  params:
    encoder_layer_sizes: [784, 128]
    latent_size: 3
    decoder_layer_sizes: [3, 128, 784]
    input_shape: [28, 28, 1]
    latent_dim: 2

optimizer:
  name: Adam
  params:
    lr: 0.001
    warmup_steps: 1000
    total_steps: 10000
    start_factor: 0.01
    eta_min: 1.0e-6